fix retry

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -66,7 +66,7 @@ jobs:
         mode: check
         environment: develop
 
-    - name: Check if Lock is Set (with retries)
+    - name: Check if Lock is Still Held (with retries)
       if: ${{ steps.check_lock.outputs.locked == 'true' }}
       run: |
         retry_count=0
@@ -75,10 +75,13 @@ jobs:
           sleep 20  # Wait 20 seconds between checks
           retry_count=$((retry_count + 1))
 
-          # Re-check the lock
-          gh workflow run github/lock@v2.3.0 \
-            --with mode=check \
-            --with environment=develop
+          # Re-check the lock output
+          locked=$(gh action status -w ${{ github.workflow }} -j check_lock)
+          # Update the output variable based on the status
+          if [[ $locked == *"failure"* ]]; then
+            echo "Lock acquisition failed in check_lock step."
+            exit 1
+          fi
         done
 
         if [[ ${{ steps.check_lock.outputs.locked }} == 'true' ]]; then
