check file changes

diff --git a/.github/workflows/qa-deploy-command.yml b/.github/workflows/qa-deploy-command.yml
--- a/.github/workflows/qa-deploy-command.yml
+++ b/.github/workflows/qa-deploy-command.yml
@@ -13,12 +13,12 @@ jobs:
           token: ${{ secrets.PAT }}
           fetch-depth: 0
 
-      - name: Get list of changed files
-        id: changed-files
+      - name: Check for changes in .github/workflows
         run: |
           changed_files=$(gh pr diff --name-only)
-          echo "changed_files=$changed_files" >> $GITHUB_OUTPUT
-          echo "Changed files:"
-          echo "$changed_files"
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          if echo "$changed_files" | grep -q '^\.github/workflows/'; then
+            echo "Changes detected in .github/workflows directory. Exiting workflow."
+            exit 1  # Exit with failure status
+          fi
+      - name: echo next
+        run: echo "This is next"
